config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :show, :new, :create, :destroy, :update, :edit]
  resources :products, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :offers, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  get "/dashboards", to: "dashboards#dashboard", as: "dashboards"
  get "/dashboards/:id", to: "dashboards#show", as: "dashboards_product"
  get "/dashboards/product/:product_id/offer/:id/validate", to: "dashboards#validate", as: "validate_offer"
  get "/dashboards/product/:product_id/offer/:id/refused", to: "dashboards#refused", as: "refused_offer"
  get "/transporter/sign_up", to: "transporters#new", as: "sign_up_transporter"
  post "transporter/create", to: "transporters#create", as: "registration_session"
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized

  def dashboard
    @product = current_user.products
    @products = @product.order("created_at DESC")
    @offers = {}

    @products.each do |product|
      product_offers = product.offers.joins(:hypothese)

      @offers[product.id] = {
        demenagement: product_offers.where(hypotheses:{ name: "Déménagement" }).order(:price).first,
        transport: product_offers.where(hypotheses:{ name: "Transport" }).order(:price).first
      }
    end

    @hypothese1_products = Product.joins(offers: :hypothese).where(hypotheses:{ name: "Déménagement" }).group(:id)
    @hypothese2_products = Product.joins(offers: :hypothese).where(hypotheses:{ name: "Transport" }).group(:id)

    # product.offers.order(:price).first


    # @orders = current_user.bookings
    # @products = current_user.products
    if  current_user.transporter
      @transporter = Transporter.find_by(user: current_user.id)
      @offers = @transporter.offers
    else

    end

    @hypothese1 = []
    @hypothese2 = []

    @products.each do |product|
      product.offers.each do |offer|
        if offer.hypothese_id == 1
          @hypothese1 << offer
        else offer.hypothese_id == 2
          @hypothese2 << offer
        end
      end
    end
    @hypothese1.sort_by do |b|
      b.price
    end
  end


  def show

    @product = Product.find(params[:id])
    @offers =  Offer.where(product: @product)
  end

  def validate
    @product = Product.find(params[:product_id])
    @offer = Offer.find(params[:id])
    authorize @offer
    @product.status = 1
    @offer.status = 1
    other_offer = Offer.where(product: @product )
    other_offer.each do |offer|
      offer.status = 2
      offer.save
    end
    # chercher les autres offres puis status validé
    @product.save
    @offer.save
    respond_to do |format|
      # format.html { redirect_to dashboards_path }
      format.js
    end
      # <-- will render `app/views/reviews/create.js.erb`
    # redirect_to dashboards_path
  end

  def refused
    @product = Product.find(params[:product_id])
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.status = 2
    @product.save
    @offer.save
    respond_to do |format|
      # format.html { redirect_to dashboards_path }
      format.js
    end
  end
end

app/views/dashboard/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="content">
          <%= @product.title %>
          <%= @product.description %>
          <%= @product.status %>
          <%= link_to "retour au produit", products_path %>
          <%= link_to "Faire une offre", new_product_offer_path(@product) %>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="content">
          <% @offers.each do |offer|  %>
            <% if offer.status == true %>
            <% end %>
            <div class="offer">
              <%= offer.transporter.user.first_name %>
              <%= offer.description %>
              <%= offer.price %>
              <% if @product.user == current_user %>
                <%= link_to "Validé", validate_offer_path(@product,offer)  %>
                <%= link_to "Refusé", refused_offer_path(@product,offer)  %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>