config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :show, :new, :create, :destroy, :update, :edit]
  resources :products, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :offers, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  get "/dashboards", to: "dashboards#dashboard", as: "dashboards"
  get "/dashboards/:id", to: "dashboards#show", as: "dashboards_product"
  get "/dashboards/product/:product_id/offer/:id/validate", to: "dashboards#validate", as: "validate_offer"
  get "/dashboards/product/:product_id/offer/:id/refused", to: "dashboards#refused", as: "refused_offer"
  get "/transporter/sign_up", to: "transporters#new", as: "sign_up_transporter"
  post "transporter/create", to: "transporters#create", as: "registration_session"
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="footer-team hidden-xs hidden-sm">
      <p><%= image_tag "adrien.jpg", class: "avatar-team" %></p>
      <p> <%= image_tag "vincent.jpg", class: "avatar-team"  %></p>
      <p> <%= image_tag "adam.jpg", class: "avatar-team"  %></p>
      <p> <%= image_tag "david.jpg", class: "avatar-team"  %></p>
    </ul>
  </div>
  <div class="logo">
    <p><%= link_to "O Diable", root_path %></p>
    </div>
  <div class="footer-links">
  <h1>
    Made with Love by ©Odiable at Le Wagon
  </h1>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>

  <div class="navbar-container">
   <div class="logo">
    <p><%= link_to "O Diable", root_path %></p>
    </div>


    <div class="liens hidden-xs">
      <%= link_to "Voir les annonces", products_path  %>
    </div>
    <% if current_user.transporter? %>
    <% else %>
    <div class="liens hidden-xs">
      <%= link_to "Devenir transporteur", sign_up_transporter_path %>
    </div>
    <% end %>

    <div class="mydashboard">
    <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'btn-logout'  %>
      <%= link_to "Tableau de bord", dashboards_path, class: 'dashboard-btn'  %>
    </div>
  </div>
    <% else %>
    <div class="navbar-container">
    <div class="logo">
    <p><%= link_to "O Diable", root_path %></p>
    </div>

    <div class="liens">
      <%= link_to "Voir les annonces", products_path  %>
      <%= link_to "Devenir transporteur", sign_up_transporter_path %>
    </div>
      <div class="btn-container">
        <%= link_to "S'inscrire", new_user_registration_path, class: "btn-signin" %>
        <%= link_to "Se connecter", user_session_path,  class: "btn-signup" %>
      </div>
</div>
<% end %>