config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :show, :new, :create, :destroy, :update, :edit]
  resources :products, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :offers, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  get "/dashboards", to: "dashboards#dashboard", as: "dashboards"
  get "/dashboards/:id", to: "dashboards#show", as: "dashboards_product"
  get "/dashboards/product/:product_id/offer/:id/validate", to: "dashboards#validate", as: "validate_offer"
  get "/dashboards/product/:product_id/offer/:id/refused", to: "dashboards#refused", as: "refused_offer"
  get "/transporter/sign_up", to: "transporters#new", as: "sign_up_transporter"
  post "transporter/create", to: "transporters#create", as: "registration_session"
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/views/pages/home.html.erb
<div class="banner-container">
  <div class="banner-content">
  <br><h1 id="specific">O Diable</h1>
  <h2>Trouvez un transporteur pour vos objets volumineux n'a jamais été aussi simple !</h2>
  <% if user_signed_in? && current_user.transporter? %>
    <%= link_to "Voir les annonces", products_path, class: 'btn-banner' %>
  <% else %>
    <%= link_to "Déposer une annonce", new_product_path, class: 'btn-banner' %>
  <% end %>
  </div>

</div>

<div class="container-produit-home">
    <div class="descriptif-produit-home">
      <div class="picture-home-large",>
        <%= image_tag("large-product.jpg") %>
      </div>
      <h1>LARGE (L)</h1>
      <p>Mobilier de taille très importante: Table, canapé, armoire ...</p>
    </div>
    <div class="descriptif-produit-home">
      <h1>MOYEN (M)</h1>
      <p>Mobilier de taille moyenne: Commode, table, rangement ...</p>
      <div class="picture-home-medium">
        <%= image_tag("medium-product.jpg") %>
      </div>
    </div>
    <div class="descriptif-produit-home">
      <h1>PETIT (S)</h1>
      <p>Mobilier de taille petite: Chaises, table de nuit, etagère ...</p>
      <div class="picture-home-small">
      <%= image_tag("small-product.jpg")  %>
      </div>
    </div>
</div>

<div class="container-transporter">

    <div class="contenu-home-transporteur">
      <h2> Devenez transporteur !</h2>
      <p>Ammortissez votre véhicule plus sereinement.</p>
    </div>

    <div class="btn-home-transporteur">
      <%= link_to "Devenir transporteur", sign_up_transporter_path, class: 'btn-banner btn-transporter' %>
    </div>

</div>

<div class="recapitulatif">
  <div class="text-comment">
  <h1>Comment ça marche ?</h1>
  </div>

  <div class="content-explication">
    <div class="card-explication">
      <i class="fas fa-edit"></i>
      <h5>  Déposez votre annonce </h5>
    </div>

    <div class="card-explication">
     <i class="fas fa-envelope"></i>
      <h5> Recevez des propositions</h5>

    </div>

    <div class="card-explication">
      <i class="fas fa-check-square"></i>
      <h5>  Validez votre réservation</h5>
      <!-- <p>Choisissez parmi plusieurs propositions celle qui vous convient le mieux</p> -->
    </div>
  </div>
</div>