config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :show, :new, :create, :destroy, :update, :edit]
  resources :products, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :offers, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  get "/dashboards", to: "dashboards#dashboard", as: "dashboards"
  get "/dashboards/:id", to: "dashboards#show", as: "dashboards_product"
  get "/dashboards/product/:product_id/offer/:id/validate", to: "dashboards#validate", as: "validate_offer"
  get "/dashboards/product/:product_id/offer/:id/refused", to: "dashboards#refused", as: "refused_offer"
  get "/transporter/sign_up", to: "transporters#new", as: "sign_up_transporter"
  post "transporter/create", to: "transporters#create", as: "registration_session"
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized

  def dashboard
    @product = current_user.products
    @products = @product.order("created_at DESC")
    @offers = {}

    @products.each do |product|
      product_offers = product.offers.joins(:hypothese)

      @offers[product.id] = {
        demenagement: product_offers.where(hypotheses:{ name: "Déménagement" }).order(:price).first,
        transport: product_offers.where(hypotheses:{ name: "Transport" }).order(:price).first
      }
    end

    @hypothese1_products = Product.joins(offers: :hypothese).where(hypotheses:{ name: "Déménagement" }).group(:id)
    @hypothese2_products = Product.joins(offers: :hypothese).where(hypotheses:{ name: "Transport" }).group(:id)

    # product.offers.order(:price).first


    # @orders = current_user.bookings
    # @products = current_user.products
    if  current_user.transporter
      @transporter = Transporter.find_by(user: current_user.id)
      @offers = @transporter.offers
    else

    end

    @hypothese1 = []
    @hypothese2 = []

    @products.each do |product|
      product.offers.each do |offer|
        if offer.hypothese_id == 1
          @hypothese1 << offer
        else offer.hypothese_id == 2
          @hypothese2 << offer
        end
      end
    end
    @hypothese1.sort_by do |b|
      b.price
    end
  end


  def show

    @product = Product.find(params[:id])
    @offers =  Offer.where(product: @product)
  end

  def validate
    @product = Product.find(params[:product_id])
    @offer = Offer.find(params[:id])
    authorize @offer
    @product.status = 1
    @offer.status = 1
    other_offer = Offer.where(product: @product )
    other_offer.each do |offer|
      offer.status = 2
      offer.save
    end
    # chercher les autres offres puis status validé
    @product.save
    @offer.save
    respond_to do |format|
      # format.html { redirect_to dashboards_path }
      format.js
    end
      # <-- will render `app/views/reviews/create.js.erb`
    # redirect_to dashboards_path
  end

  def refused
    @product = Product.find(params[:product_id])
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.status = 2
    @product.save
    @offer.save
    respond_to do |format|
      # format.html { redirect_to dashboards_path }
      format.js
    end
  end
end

app/views/dashboards/_offer.html.erb
<% if offer.status == "Refusé" %>
<% elsif offer.status == "Validé" %>
  <div class="dash-transporter-offer">
      <div class="presentation-hypo">
         <p>
           <i class="fas fa-home truck"></i>
          Chez moi
        </p>
      </div>
     <div class="salut">
       <p style= "font-weight: bold;">
         <%= image_tag offer.transporter.user.photo, class: "dash-offer-user" %>
         <%= offer.transporter.user.first_name %>
       </p>
     <!-- <div class="dash-offer-link"> -->
        <div class="offers-prices">
          <div class="flex-link">
            <div class="dash-prix">
              <p><%= offer.price %> € </p>
            </div>
          </div>
        </div>
        <div class="offers-prices">
         <p><%= offer.description.capitalize %></p>
        </div>
      </div>
    </div>
<% else  %>
  <!-- <div class="dash-transporter-offers"> -->
  <% if offer.hypothese.name == "Déménagement" %>
    <div class="dash-transporter-offer">
      <div class="presentation-hypo">
        <p>
           <i class="fas fa-home truck"></i>
          Chez moi
        </p>
      </div>
     <div class="salut">
       <p style= "font-weight: bold;">
         <%= image_tag offer.transporter.user.photo, class: "dash-offer-user" %>
         <%= offer.transporter.user.first_name %>
       </p>
     <!-- <div class="dash-offer-link"> -->
        <div class="offers-prices">
          <div class="flex-link">
            <div class="dash-prix">
              <p><%= offer.price %> € </p>
            </div>
            <%= link_to validate_offer_path(product, offer),  remote: true do %>
              <i class="far fa-2x fa-check-circle green"></i>
            <% end %>
            <%= link_to refused_offer_path(product, offer),remote: true do %>
              <i class="far fa-2x fa-times-circle red"></i>
            <% end %>
          </div>
        </div>
        <div class="offers-prices">
         <p><%= offer.description.capitalize %></p>
        </div>
      </div>
    </div>
  <% else %>
     <div class="dash-transporter-offer">
      <div class="presention-hypos">
        <p>
           <i class="fas fa-truck truck"></i>
          Pied du camion
        </p>
      </div>
      <div class="salut">
        <p style= "font-weight: bold;">
          <%= image_tag offer.transporter.user.photo, class: "dash-offer-user" %>
          <%= offer.transporter.user.first_name %>
        </p>
      <!-- <div class="dash-offer-link"> -->
        <div class="offers-prices">
         <div class="flex-link">
          <div class="dash-prix">
            <p><%= offer.price %> € </p>
          </div>
         <%= link_to validate_offer_path(product, offer),  remote: true do %>
            <i class="far fa-2x fa-check-circle green"></i>
            <% end %>
          <%= link_to refused_offer_path(product, offer),remote: true do %>
            <i class="far fa-2x fa-times-circle red"></i>
          <% end %>
         </div>
        </div>
          <div class="offers-prices">
            <p><%= offer.description.capitalize %></p>
          </div>
      </div>
        <!-- <div class="offerss-link"> -->
        <!-- </div> -->
      <!-- </div> -->
    </div>
  <% end %>
  <!-- </div> -->
<% end %>

<%#= @hypotheses1.each do |offer| %>
  <%# if offer.product == product %>
    <%# raise %>
  <%# end %>
<%#end %>

app/views/dashboards/dashboard.html.erb
<div class="dashboard">
  <% if current_user.transporter %>
    <div class="dash-sidebar">
      <div class="mon-avatar">
        <div class="mon-avatar-photo">
          <%= image_tag current_user.photo, crop: :fill , class: "mon-avatar-photo" %>
        </div>
        <div class="mon-avatar-name">
          <%= current_user.first_name.capitalize %>
        </div>
      </div>
        <div class="mes-offres act">
          <h3>Mes Offres</h3>
        </div>
        <div class="mes-produits">
          <h3><%= "Mes Produits" %></h3>
        </div>
        <div class="mon-profil">
          <h3>Mon Profil</h3>
        </div>
        <div class="mon-historique">
          <h3>Historique</h3>
        </div>
    </div>
    <% else %>
    <div class="dash-sidebar">
      <div class="mon-avatar">
        <div class="mon-avatar-photo">
           <%= image_tag current_user.photo, crop: :fill , class: "mon-avatar-photo" %>
          <!-- <#%= link_to image_tag current_user.photo, crop: :fill  %> -->
        </div>
        <div class="mon-avatar-name">
          <%= current_user.first_name.capitalize %>
        </div>
      </div>

        <div class="mes-offres">
          <h3>Mes Offres</h3>
        </div>
        <div class="mes-produits act spe-prod-dispense">
          <h3><%= "Mes Produits" %></h3>
        </div>
        <div class="mon-profil">
          <h3>Mon Profil</h3>
        </div>
        <div class="mon-historique">
          <h3>Historique</h3>
        </div>
    </div>
  <% end %>

 <% if current_user.transporter  %>
  <div class="container-fluid">
    <div class="container-card-dash">
    <div class="row">
      <% @offers.each do |offer| %>
        <div class="col-xs-12 ">
          <div class="dash-card">
            <div class="dash-card-photo" style="background-image: url(<%= cl_image_path offer.product.photo,crop: :fit %>)">
            </div>

            <div class="dash-card-description">
            <!--   <div class="dash-description-title">
                <p><%#product.title.capitalize %></p>
              </div> -->
                  <div class="dash-description-desc">
                    <h3><%= offer.product.title.capitalize %></h3>
                  </div>
              <div class="dash-desc-address">
                <div class="dash-description-aaad">
                  <div class="line-dash">
                  </div>
                  <div class="dash-description-ad">
                    <i class="far fa-circle"></i>
                    <p><%= offer.product.ad %></p>
                  </div>

                  <div class="dash-description-aa">
                    <i class="fas fa-circle"></i>
                    <p><%= offer.product.aa %></p>
                  </div>

                </div>

                <div class="date-dash-transp">
                  <div class="offer-dasth-status">
                      <%= offer.status %>
                  </div>
                  <div class="date-delivery">

                  <p><%= offer.product.date_delivery %></p>
                  </div>
                </div>
              </div>
              <div class="button-dash-ticket">
                <div class="offer-price-dash">
                <p>  <%= offer.price %>€ </p>
                </div>
                <div class="offer-description-dash">
                  <h4> <%= offer.description %> </h4>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% else %>
    <div class="container-fluid">
    <div class="container-card-dash">
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-xs-12 ">
          <div class="dash-card">
            <div class="dash-card-photo" style="background-image: url(<%= cl_image_path product.photo,crop: :fit %>)">
            </div>
            <div class="dash-card-description">
            <!--   <div class="dash-description-title">
                <p><%= product.title.capitalize %></p>
              </div> -->
                  <div class="dash-description-desc">
                    <h3><%= product.title.capitalize %></h3>
                  </div>
              <div class="dash-desc-address">
                <div class="dash-description-aaad">
                  <div class="dash-description-ad">
                    <i class="far fa-circle"></i>
                    <p><%= product.ad %></p>
                  </div>
                  <div class="line-dash"></div>
                  <div class="dash-description-aa">
                    <i class="fas fa-circle"></i>
                    <p><%= product.aa %></p>
                  </div>
                </div>
              </div>
              <div class="button-dash-all">
                <div class="button-dash-edit">
                  <p><a href="#" data-product-id="<%= product.id %>">Meilleures Offres</a></p>
                </div>
                <div class="my-btn-delete">
                 <p>
                   <%= link_to image_tag("icons8-editer-le-fichier-50.png"), edit_product_path(product), class: "icons-edit" %>
                    <%= link_to image_tag("icons8-supprimer-80.png"), product_path(product), method: :delete, class: "icons" %>
                    Offre(s) :  <%= product.offers.where(status: 1, status: 0).length %>
                 </p>
                </div>
              </div>
            </div>
          </div>
            <div class="dash-offer-details hidden", id="product-<%= product.id %>" data-offer-id="<%= product.id%>">
              <% if @offers[product.id][:demenagement] %>
                <div id="offer-<%= @offers[product.id][:demenagement].id %>">
                  <%= render "dashboards/offer", offer: @offers[product.id][:demenagement], product: product%>
                </div>
              <% end %>

              <% if @offers[product.id][:transport] %>
                <div id="offer-<%= @offers[product.id][:transport].id %>">
                  <%= render "dashboards/offer", offer: @offers[product.id][:transport], product: product%>
                </div>
              <% end %>
           </div>
        </div>
      <% end %>
      <% end %>

    </div>
    </div>
  </div>
</div>

app/views/dashboards/dashboard_original.html.erb
<% if current_user.transporter %>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Mes Produits</a></li>
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Mes offres</a></li>
  </ul>
<% else %>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Mes Produits</a></li>
  </ul>
<% end %>
  <!-- Tab panes -->
<div class="wrap-dash" >
  <div class="container">
    <div class="tab-content">
      <div role="tajbpanel" class="tab-pane fade in active" id="home">
        <% @offers.each do |offer| %>
          <div class="col-xs-6">
            <div class="dashboard-card">
              <div class="cover">
                <%= cl_image_tag offer.product.photo, height: 200, width: 200, crop: :fill, class: "img-dash"%>
                <label>
                  <i>
                    <svg x="0px" y="0px" width="17px" height="17px">
                    <%= image_tag("logo-odiable", id: "logo-dash") %>
                    </svg>
                  </i>
                  <font>Vos offres</font>
                </label>
                <div class="title-dash2">
                  <h1>Description: <%= offer.description.capitalize %></h1>
                </div>
                <div class="description-dashboard2">
                  <%= offer.price %>€
                </div>
                <div class="status">
                  <p><%= offer.status %></p>
                </div>
                <div class="address-depart">
                  <p><%= offer.product.ad %></p>
                </div>
                <div class="address-arrive">
                  <p><%= offer.product.aa %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>


      </div>
      <div role="tabpanel" class="tab-pane fade" id="profile">
      </div>
      <div role="tabpanel" class="tab-pane fade" id="messages">
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-xs-12">
              <div class="dashboard-card">
                <!-- <div class="content-top-dash"> -->
                  <div class="cover">
                    <%= cl_image_tag product.photo, height: 200, width: 200, crop: :fill, class: "img-dash"%>
                    <label>
                      <i>
                        <svg x="0px" y="0px" width="17px" height="17px">
                        <%= image_tag("logo-odiable", id: "logo-dash") %>
                        </svg>
                      </i>
                      <font>Votre annonce en cours</font>
                    </label>
                    <div class="contenu-dash-card">
                      <div class="title-dash">
                        <h1><%= product.title.capitalize %></h1>
                      </div>
                      <div class="description-dashboard">
                        <strong>Description:</strong>
                        <%= product.description.capitalize %>
                      </div>
                      <div class="address-depart">
                        <p><%= product.ad %></p>
                      </div>
                      <div class="addres-arrive">
                        <p><%= product.aa %></p>
                      </div>
                    </div>
                    <div class="button-dash-edit">
                      <p><%= link_to "Editer", edit_product_path(product) %></p>
                    </div>
                    <div class="button-dash-suppr">
                      <p><%= link_to "Supprimer", product_path(product), method: :delete %></p>
                    </div>
                  </div>
                  <div class="info">
                    <div class="recipe">
                      <a href="#" data-product-id="<%= product.id %>">
                        <i>
                          <svg x="0px" y="0px" width="26px" height="28px">
                            <g>
                              <path d="M 8.5 20 L 8.5 21 L 17.5 21 L 17.5 20 L 8.5 20 ZM 8.5 16 L 8.5 17 L 17.5 17 L 17.5 16 L 8.5 16 ZM 8.5 12 L 8.5 13 L 17.5 13 L 17.5 12 L 8.5 12 ZM 20 0 C 19.4477 0 19 0.4477 19 1 L 19 6 C 19 6.5523 19.4477 7 20 7 C 20.5523 7 21 6.5523 21 6 L 21 1 C 21 0.4477 20.5523 0 20 0 ZM 13 0 C 12.4477 0 12 0.4477 12 1 L 12 6 C 12 6.5523 12.4477 7 13 7 C 13.5523 7 14 6.5523 14 6 L 14 1 C 14 0.4477 13.5523 0 13 0 ZM 6 0 C 5.4477 0 5 0.4477 5 1 L 5 6 C 5 6.5523 5.4477 7 6 7 C 6.5523 7 7 6.5523 7 6 L 7 1 C 7 0.4477 6.5523 0 6 0 ZM 15 4 L 18 4 L 18 3 L 15 3 L 15 4 ZM 8 4 L 11 4 L 11 3 L 8 3 L 8 4 ZM 3 4 L 4 4 L 4 3 L 3 3 C 1.3431 3 0 4.3431 0 6 L 0 25 C 0 26.6569 1.3431 28 3 28 L 23 28 C 24.6569 28 26 26.6569 26 25 L 26 6 C 26 4.3431 24.6569 3 23 3 L 22 3 L 22 4 L 23 4 C 24.1046 4 25 4.8954 25 6 L 25 25 C 25 26.1046 24.1046 27 23 27 L 3 27 C 1.8954 27 1 26.1046 1 25 L 1 6 C 1 4.8954 1.8954 4 3 4 Z" fill="#ffffff"/>
                            </g>
                          </svg>
                        </i>
                       <font>Voir Offres</font>
                      </a>
                    </div>
                    <div class="content-bottom">
                      <table width="100%" cellpadding="0" cellspacing="0">
                        <tr>
                          <td align="left" valign="middle" class="pad-right">
                          </td>
                          <td align="left" valign="middle"></td>
                          <td width="20" rowspan="2" class="border-right">&nbsp;</td>
                          <td width="140" rowspan="2" align="center" valign="middle">
                            <h1>4.8/5</h1>
                            <span class="stars">
                              <em style="width: 91%"></em>
                            </span><br />
                          </td>
                        </tr>
                        <tr>
                          <td align="left" valign="middle" class="pad-right"><strong>Transporteurs:</strong></td>
                          <td align="left" valign="middle" class="consumers">
                            <img src="" />
                            <img src="" />
                            <img src="" />
                            <img src="" />
                            <span>(+4)</span>
                          </td>
                        </tr>
                      </table>
                    </div>
                  </div>
                </div>
                <div class="dash-offer-details hidden", data-offer-id="<%= product.id%>">
                  <% product.offers.each do |offer| %>
                  <% if offer.status == "Refusé" %>
                  <% elsif offer.status == "Validé" %>
                    <div class="dash-transporter-offer">
                      <%= image_tag "logo-diable.jpg", class: "dash-offer-user" %>
                      <div class="dash-offer-desc">
                        <p><%= offer.description.capitalize %></p>
                        <p><%= offer.price %> € </p>
                      </div>
                    </div>
                  <% else  %>
                    <div class="dash-transporter-offer">
                      <%= image_tag "logo-diable.jpg", class: "dash-offer-user" %>
                      <div class="dash-offer-desc">
                        <p><%= offer.description.capitalize %></p>
                        <p><%= offer.price %> € </p>
                      </div>
                      <div class="dash-offer-link">
                        <%= link_to "Valider", validate_offer_path(product, offer), class: "button-dash-edit" %>
                        <%= link_to "Refused", refused_offer_path(product, offer), class: "button-dash-suppr" %>
                      </div>
                    </div>
                  <% end %>
                  <% end %>
                <!-- </div> -->
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/refused.js.erb
function refreshOffer(innerHTML) {
  console.log("bonjour")
  const newOffer = document.getElementById("product-<%= @product.id %>");
  newOffer.innerHTML = innerHTML;
}



refreshOffer('<%= j render "dashboards/offer", offer: @offer, product: @product%>');

app/views/dashboards/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="content-dashboard-show">
            <%= @product.title %>
            <%= @product.description %>
            <%= @product.status %>
            <%= link_to "retour au dashboard", dashboards_path %>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="content-dashboard-show">
          <% @offers.each do |offer|  %>
            <div class="offer">
              <%= offer.transporter.user.first_name %>
              <%= offer.description %>
              <%= offer.price %>
              <% if @product.user == current_user %>
                <%= link_to "Validé", validate_offer_path(@product,offer)  %>
                <%= link_to "Refusé", refused_offer_path(@product,offer)  %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/validate.js.erb
function refreshOffer(innerHTML) {
  console.log("bonjour")
  const newOffer = document.getElementById('product-<%= @product.id %>');
  // newOffer.remove()
  newOffer.innerHTML = innerHTML;
}



refreshOffer('<%= j render "dashboards/offer", offer: @offer, product: @product%>');